# Generated by Django 5.2 on 2025-05-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0005_naturaleza_movimiento_descripcion_debilidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodo_evolucion", models.CharField(max_length=100)),
                ("nivel_evolucion", models.IntegerField(blank=True, null=True)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evoluciones",
                        to="pokedex.pokemon",
                    ),
                ),
                (
                    "pokemon_evolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolucion_de",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolución",
                "verbose_name_plural": "Evoluciones",
            },
        ),
    ]
